class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start2'
        self.MirrorCommand = 'mirror2'
        self.UnzipMirrorCommand = 'unzipmirror2'
        self.TarMirrorCommand = 'tarmirror2'
        self.CancelMirror = 'cancel2'
        self.CancelAllCommand = 'cancelall2'
        self.ListCommand = 'list2'
        self.StatusCommand = 'status2'
        self.AuthorizedUsersCommand = 'users2'
        self.AuthorizeCommand = 'authorize2'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo2'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping2'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stats2'
        self.HelpCommand = 'help2'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest2'
        self.CloneCommand = 'clone2'
        self.CountCommand = 'count2'
        self.WatchCommand = 'watch2'
        self.TarWatchCommand = 'tarwatch2'
        self.DeleteCommand = 'del2'
        self.UsageCommand = 'usage2'
        self.MediaInfoCommand = 'mediainfo2'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update2'

BotCommands = _BotCommands()
