class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start1'
        self.MirrorCommand = 'mirror1'
        self.UnzipMirrorCommand = 'unzipmirror1'
        self.TarMirrorCommand = 'tarmirror1'
        self.CancelMirror = 'cancel1'
        self.CancelAllCommand = 'cancelall1'
        self.ListCommand = 'list1'
        self.StatusCommand = 'status1'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping1'
        self.RestartCommand = 'restart1'
        self.StatsCommand = 'stats1'
        self.HelpCommand = 'help2'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest1'
        self.CloneCommand = 'clone1'
        self.CountCommand = 'count1'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch1'
        self.DeleteCommand = 'del1'
        self.UsageCommand = 'usage1'
        self.MediaInfoCommand = 'mediainfo1'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update1'

BotCommands = _BotCommands()
